dickensnotes/ddnp

src/pages/notes/bleak-house/index.mdx
Corrected a few errors I noticed in my last round of revisions.
=> Made corrections to TOC and WC

src/pages/introduction/general.mdx
=> Italicized novel titles

src/pages/notes/bleak-house/index.mdx
I guess italics aren't possible in Title header
=> Fixed Title in BH intro

src/components/Header.astro, src/components/Nav.jsx
Edited descriptions in Header.astro
=> Anna_navbardescriptions

src/pages/usage/teaching.mdx
Created the headings and added content to the Teaching with the DDNP page
=> Added headings and content to teaching page

src/pages/usage/teaching.mdx
Minor edits to formatting and ToC to fix links
=> Edits to teaching page

src/pages/about/editing-the-notes.mdx
Merging the content for Editing-the-Notes page into Main
=> Nov2_EditingPage_add

src/pages/about/editing-the-notes.mdx, src/pages/notes/david-copperfield/index.mdx, src/pages/usage/guide.mdx
Updating and correcting titles and header info for pages
=> Minor updates and edits to the Headers and Titles to Editing, User Guide, and DC intro pages

src/components/Hero.astro
edited description text in hero image on homepage
=> edited description text in hero image on homepage

src/pages/index.astro
Edited card descriptions on homepage
=> Edited card descriptions on homepage

src/pages/introduction/general.mdx, src/pages/introduction/scholarly.mdx
Edited titles to both intros and edited subtitle for first scholarly intro section.
=> Edited titles to both intros and edited subtitle for first scholarly intro section.

src/pages/about/colophon.mdx, src/pages/usage/guide.mdx
Added content to user guide (minus Searching section)
=> Build out the User Guide with images; minor edit to text of Colophon

src/pages/usage/guide.mdx
=> Edits to fix links and images in User Guide

src/components/Header.astro, src/pages/credits-and-acknowledgements/index.mdx, src/pages/notes/additional-working-notes/index.mdx
Fixes #105 
Fixes #89 
cc @grenerad @annamgibson
=> Add new pages

src/components/ImageWithCaption.astro
=> Center and add drop shadow to images

src/pages/about/bibliography.mdx, src/pages/about/editing-the-notes.mdx
Merging text additions for "About" section into main
=> Added text for Transcription Process and Bibliography intro

src/pages/about/bibliography.mdx
Merging bibliography into main
=> Added full bibliography entries

src/pages/about/editing-the-notes.mdx, src/pages/about/team.mdx
Anna and I discussed adjustments to the "how to cite" for certain pages; merging those edits into main.
=> removed and edited 'how to cite' on pages where appropriate

src/components/Header.astro
Fixes #75 
cc @annamgibson & @grenerad
=> Add link to Search

src/pages/about/editing-the-notes.mdx
Added images to Editing the Notes section
=> Add images and captions to Editing section

src/components/ImageWithCaption.astro, src/pages/introduction/general.mdx
Based on whether there are marked as coming from V&A
=> Conditionally constrain height of some images

src/pages/about/team.mdx
Added content to About the Team page
=> Added content on Team page and changed metadata descriptor

src/pages/about/bibliography.mdx, src/pages/about/editing-the-notes.mdx, src/pages/about/team.mdx, src/pages/credits-and-acknowledgements/index.mdx, src/pages/introduction/general.mdx, src/pages/introduction/scholarly.mdx, src/pages/notes/additional-working-notes/index.mdx, src/pages/notes/bleak-house/index.mdx, src/pages/notes/david-copperfield/index.mdx, src/pages/search/index.md, src/pages/usage/guide.mdx, src/pages/usage/teaching.mdx
Added or edited metadata descriptions for all pages that require it
=> Added descriptions to metadata for all pages.

src/components/MiradorLink.astro
=> Update text and style on card

src/pages/notes/david-copperfield/index.mdx
Added text and image and How to Cite for David Copperfield placeholder introduction
=> Added placeholder text and image for Copperfield

src/pages/notes/david-copperfield/index.mdx
adding mirador card link to DC homepage
=> Added Mirador Card for DC

src/components/Footer.astro
=> Adjust footer styling

src/components/Footer.astro, src/layouts/notes.astro, src/layouts/page.astro
=> Add brand color to underline links

src/pages/usage/guide.mdx
Added provisional search language to the user guide for review.
=> Added provisional search language to the user guide for review.

src/pages/index.astro
=> Update home card links to webp images

src/components/Header.astro
=> Switch order of notes in the nav

src/components/Card.astro, src/components/Hero.astro, src/components/MiradorLink.astro, src/pages/about/bibliography.mdx, src/pages/about/editing-the-notes.mdx, src/pages/about/team.mdx, src/pages/introduction/general.mdx, src/pages/usage/teaching.mdx
=> Add fixes for accessibility issues, mostly heading levels

package.json, pnpm-lock.yaml, src/components/Header.astro, src/components/NavPopover.jsx
=> Add fontawesome icons to nav [WIP]

src/pages/index.astro, src/pages/usage/guide.mdx
Edited User Guide to correct error about thumbnail display. 
Edited description on index.
=> Edited User Guide to correct error about thumbnail display. Edited description on index.

src/pages/usage/teaching.mdx
=> Update pdf path

package.json, src/pages/about/editing-the-notes.mdx, src/pages/usage/guide.mdx
Fixed internal hyperlinks that had errors
=> Fixing broken internal links

src/components/MainHead.astro, src/pages/about/colophon.mdx, src/pages/introduction/general.mdx, src/pages/introduction/scholarly.mdx, src/pages/notes/bleak-house/index.mdx
Edited twitter card fields (and deleted trailing commas); Edited to mention Vercel in Colophon
=> Edited twitter card fields and colophon

src/components/Footer.astro, src/components/Header.astro, src/pages/index.astro
Changes to the home page and nav bar and footer for v1.1 release
=> Reordered novels on homepage cards and drop-down menu; updated Version in footer

src/pages/about/editing-the-notes.mdx
Added project version history to Editing the Notes page
=> Added Project Version History to Editing the Notes page

src/pages/about/bibliography.mdx
Added WN Manuscripts section to bibliography
=> Added WN Manuscripts section to biblography

src/pages/notes/david-copperfield/index.mdx
Attempting to fix italics and apostrophe in heading
=> fixing italics in headings
